[main][fix] distribution support v2 liquidity
alpaca-finance/alpaca-v2-money-market pull request #358
Opened 2023-05-16 06:26 UTC by m100alpaca

## Description
- add v2 swap in distribution
- add v2 test in distribution

## Why?
- Some tokens might have not liquidity on v3. So we need to check v2 liquidity first.
- If there is no liquidity on both v2 and v3. Then we skip current token and distribute next token.

## ChangeLogs:

### Link to story (if available)

2023-05-16 06:47 UTC, 69alpacas requested changes

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +  constructor() {}
```suggestion
```

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +  mapping(address => mapping(address => PathParams)) internal paths;
add comment about what is mapped to what e.g.
```
// sourceToken => destinationToken => pathParams
```

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +  function setPaths(PathParams[] calldata _inputs) external {
only owner

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +      // sanity check. router will revert if pair doesn't exist
```suggestion
      // sanity check. router will revert if pair in path doesn't exist
```

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +      paths[_path[0]][_path[_path.length - 1]] = _params;
1. add sanity check if `_source` and `_destination` token matched `_path[0]` and `_path[length-1]`
2. should we also set `paths[dest][source]` as well?

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/reader/PCSV2PathReader.sol
> +  function getPath(address _source, address _destination) external view returns (PathParams memory) {
this function is not necessary. can get from `paths` state var like in `UniV3PathReader`

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
>          IERC20(_token).safeTransfer(revenueTreasury, _revenueAmount);
use cached variable

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          bytes memory _path = pathReaderV3.paths(_token, revenueToken);
redundant call to get path

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          }
`_success` doesn't do anything here since already emit inside `_swapToken`. consider remove it or handle error outside.

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          }
same for v2 swap

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          bytes memory _path = pathReaderV3.paths(_token, revenueToken);
same for v2 swap

2023-05-16 06:47 UTC, 69alpacas commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +        } else {
suggest refactor to flow control like this
```
bytes memory _v3Path = getV3Path
if (_v3Path.length != 0) doSwapV3
else {
  bytes memory _v2Path = getV2Path
  if (_v2Path.length == 0) revert
  doSwapV2
}
```

2023-05-16 07:16 UTC, m100alpaca commented on solidity/contracts/reader/PCSV2PathReader.sol
> +  function getPath(address _source, address _destination) external view returns (PathParams memory) {
Cannot do it the same way as v3 Reader. Due to returns is struct, compiler will be failed

2023-05-16 07:54 UTC, m100alpaca commented on solidity/contracts/reader/PCSV2PathReader.sol
> +      paths[_path[0]][_path[_path.length - 1]] = _params;
1. We don't have to sanity check `_source` and `_destination`. Since we extract it from the given path.
2. Should set separately, to support some cases that swap `tokenA` to `tokenB` is not the same route.

2023-05-16 08:57 UTC, alpanaca commented on solidity/contracts/reader/PCSV2PathReader.sol
> +contract PCSV2PathReader is IUniSwapV2PathReader, Ownable {
This doesn't limit to PCS only since we return router instance as well as the path
```suggestion
contract UniSwapV2LikePathReader is IUniSwapV2PathReader, Ownable {
```

2023-05-16 10:41 UTC, alpanaca commented on solidity/contracts/reader/UniSwapV2LikePathReader.sol
> +// return router, return path
```suggestion
/// @title UniSwapV2LikePathReader - Return router and part to swap on UniSwapV2-fork DEX
```

2023-05-17 09:31 UTC, alpanaca commented on script/deployments/PathReader/config/SetPCSV3Paths.s.sol
> +  function _setPath(bytes memory path) internal {
This should be name _addPath instead

2023-05-19 08:27 UTC, alpanaca commented on script/deployments/PathReader/config/SetPCSV3Paths.s.sol
> +  function _addPath(bytes memory path) internal {
should _

2023-05-22 09:42 UTC, alpanaca commented on solidity/contracts/reader/UniSwapV2LikePathReader.sol
> +      emit LogSetPath(_path[0], _path[_path.length - 1], _path);
```suggestion
      emit LogSetPath(_path[0], _path[_path.length - 1], _path);
      unchecked {
        ++_i;
      }

```

2023-05-22 09:45 UTC, alpanaca commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          bool _success = _swapTokenV3(_token, _revenueToken, _revenueAmount, _revenueTreasuryAddress, _v3Path);
can move this variable outside of if

2023-05-22 09:46 UTC, alpanaca commented on solidity/contracts/smart-treasury/SmartTreasury.sol
> +          bool _success = _swapTokenV3(_token, _revenueToken, _revenueAmount, _revenueTreasuryAddress, _v3Path);
Can even do if(!_swapTokenV3...()) {return}

2023-05-24 07:21 UTC, alpanaca approved these changes

2023-05-24 07:33 UTC, wow-alpaca approved these changes

2023-05-24 10:43 UTC, merged